name: Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: | 
          cd EncantoFrontend
          npm install
          

      - name: Build frontend
        run: |
          cd EncantoFrontend
          npm run build

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          - name: Build image
          working-directory: EncantoFrontend
          run: docker build -t israelcoaquira/encanto-frontend:latest .

      - name: Push Docker image
        run: |
          cd EncantoFrontend
          docker push israelcoaquira/encanto-frontend:latest

      - name: Deploy EC2 1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_FRONT1 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/encanto
            sudo docker compose pull
            sudo docker compose up -d

      - name: Deploy EC2 2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_FRONT2 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /opt/encanto
            sudo docker compose pull
            sudo docker compose up -d
